package net.momirealms.craftengine.core.item;

import net.momirealms.craftengine.core.util.Key;

public final class ComponentKeys {
    private ComponentKeys() {}

    public static final Key ATTRIBUTE_MODIFIERS = Key.of("minecraft", "attribute_modifiers");
    public static final Key BANNER_PATTERN = Key.of("minecraft", "banner_patterns");
    public static final Key BASE_COLOR = Key.of("minecraft", "base_color");
    public static final Key BEES = Key.of("minecraft", "bees");
    public static final Key BLOCK_ENTITY_DATA = Key.of("minecraft", "block_entity_data");
    public static final Key BLOCK_STATE = Key.of("minecraft", "block_state");
    public static final Key BLOCKS_ATTACK = Key.of("minecraft", "blocks_attacks");
    public static final Key BREAK_SOUND = Key.of("minecraft", "break_sound");
    public static final Key BUCKET_ENTITY_DATA = Key.of("minecraft", "bucket_entity_data");
    public static final Key BUNDLE_CONTENTS = Key.of("minecraft", "bundle_contents");
    public static final Key CAN_BREAK = Key.of("minecraft", "can_break");
    public static final Key CAN_PLACE_ON = Key.of("minecraft", "can_place_on");
    public static final Key CHARGED_PROJECTILES = Key.of("minecraft", "charged_projectiles");
    public static final Key CONSUMABLE = Key.of("minecraft", "consumable");
    public static final Key CONTAINER = Key.of("minecraft", "container");
    public static final Key CONTAINER_LOOT = Key.of("minecraft", "container_loot");
    public static final Key CUSTOM_DATA = Key.of("minecraft", "custom_data");
    public static final Key CUSTOM_MODEL_DATA = Key.of("minecraft", "custom_model_data");
    public static final Key CUSTOM_NAME = Key.of("minecraft", "custom_name");
    public static final Key DAMAGE = Key.of("minecraft", "damage");
    public static final Key DAMAGE_RESISTANT = Key.of("minecraft", "damage_resistant");
    public static final Key DEBUG_STICK_STATE = Key.of("minecraft", "debug_stick_state");
    public static final Key DEATH_PROTECTION = Key.of("minecraft", "death_protection");
    public static final Key DYED_COLOR = Key.of("minecraft", "dyed_color");
    public static final Key ENCHANTABLE = Key.of("minecraft", "enchantable");
    public static final Key ENCHANTMENT_GLINT_OVERRIDE = Key.of("minecraft", "enchantment_glint_override");
    public static final Key ENCHANTMENTS = Key.of("minecraft", "enchantments");
    public static final Key ENTITY_DATA = Key.of("minecraft", "entity_data");
    public static final Key EQUIPPABLE = Key.of("minecraft", "equippable");
    public static final Key FIREWORK_EXPLOSION = Key.of("minecraft", "firework_explosion");
    public static final Key FIREWORKS = Key.of("minecraft", "fireworks");
    public static final Key FOOD = Key.of("minecraft", "food");
    public static final Key GLIDER = Key.of("minecraft", "glider");
    public static final Key INSTRUMENT = Key.of("minecraft", "instrument");
    public static final Key INTANGIBLE_PROJECTILE = Key.of("minecraft", "intangible_projectile");
    public static final Key ITEM_MODEL = Key.of("minecraft", "item_model");
    public static final Key ITEM_NAME = Key.of("minecraft", "item_name");
    public static final Key JUKEBOX_PLAYABLE = Key.of("minecraft", "jukebox_playable");
    public static final Key LOCK = Key.of("minecraft", "lock");
    public static final Key LODESTONE_TRACKER = Key.of("minecraft", "lodestone_tracker");
    public static final Key LORE = Key.of("minecraft", "lore");
    public static final Key MAP_COLOR = Key.of("minecraft", "map_color");
    public static final Key MAP_DECORATIONS = Key.of("minecraft", "map_decorations");
    public static final Key MAP_ID = Key.of("minecraft", "map_id");
    public static final Key MAX_DAMAGE = Key.of("minecraft", "max_damage");
    public static final Key MAX_STACK_SIZE = Key.of("minecraft", "max_stack_size");
    public static final Key NOTE_BLOCK_SOUND = Key.of("minecraft", "note_block_sound");
    public static final Key OMINOUS_BOTTLE_AMPLIFIER = Key.of("minecraft", "ominous_bottle_amplifier");
    public static final Key POT_DECORATIONS = Key.of("minecraft", "pot_decorations");
    public static final Key POTION_CONTENTS = Key.of("minecraft", "potion_contents");
    public static final Key POTION_DURATION_SCALE = Key.of("minecraft", "potion_duration_scale");
    public static final Key PROFILE = Key.of("minecraft", "profile");
    public static final Key PROVIDES_BANNER_PATTERN = Key.of("minecraft", "provides_banner_patterns");
    public static final Key PROVIDES_TRIM_MATERIAL = Key.of("minecraft", "provides_trim_material");
    public static final Key RARITY = Key.of("minecraft", "rarity");
    public static final Key RECIPES = Key.of("minecraft", "recipes");
    public static final Key REPAIRABLE = Key.of("minecraft", "repairable");
    public static final Key REPAIR_COST = Key.of("minecraft", "repair_cost");
    public static final Key STORED_ENCHANTMENTS = Key.of("minecraft", "stored_enchantments");
    public static final Key SUSPICIOUS_STEW_EFFECTS = Key.of("minecraft", "suspicious_stew_effects");
    public static final Key TOOL = Key.of("minecraft", "tool");
    public static final Key TOOLTIP_DISPLAY = Key.of("minecraft", "tooltip_display");
    public static final Key TOOLTIP_STYLE = Key.of("minecraft", "tooltip_style");
    public static final Key TRIM = Key.of("minecraft", "trim");
    public static final Key UNBREAKABLE = Key.of("minecraft", "unbreakable");
    public static final Key USE_COOLDOWN = Key.of("minecraft", "use_cooldown");
    public static final Key USE_REMAINDER = Key.of("minecraft", "use_remainder");
    public static final Key WEAPON = Key.of("minecraft", "weapon");
    public static final Key WRITABLE_BOOK_CONTENT = Key.of("minecraft", "writable_book_content");
    public static final Key WRITTEN_BOOK_CONTENT = Key.of("minecraft", "written_book_content");
}
