package net.momirealms.craftengine.core.entity;

import net.momirealms.craftengine.core.util.Key;

public class EntityKeys {
    private EntityKeys() {}

    public static final Key BEE = Key.of("minecraft:BEE");
    public static final Key FOX = Key.of("minecraft:FOX");
    public static final Key FROG = Key.of("minecraft:FROG");
    public static final Key PANDA = Key.of("minecraft:PANDA");
    public static final Key SHEEP = Key.of("minecraft:SHEEP");
    public static final Key BOGGED = Key.of("minecraft:BOGGED");
    public static final Key SNOW_GOLEM = Key.of("minecraft:SNOW_GOLEM");
    public static final Key HOGLIN = Key.of("minecraft:HOGLIN");
    public static final Key OCELOT = Key.of("minecraft:OCELOT");
    public static final Key RABBIT = Key.of("minecraft:RABBIT");
    public static final Key TURTLE = Key.of("minecraft:TURTLE");
    public static final Key AXOLOTL = Key.of("minecraft:AXOLOTL");
    public static final Key CHICKEN = Key.of("minecraft:CHICKEN");
    public static final Key SNIFFER = Key.of("minecraft:SNIFFER");
    public static final Key ARMADILLO = Key.of("minecraft:ARMADILLO");
    public static final Key COD = Key.of("minecraft:COD");
    public static final Key SALMON = Key.of("minecraft:SALMON");
    public static final Key TROPICAL_FISH = Key.of("minecraft:TROPICAL_FISH");
    public static final Key PUFFERFISH = Key.of("minecraft:PUFFERFISH");
    public static final Key TADPOLE = Key.of("minecraft:TADPOLE");
    public static final Key COW = Key.of("minecraft:COW");
    public static final Key MOOSHROOM = Key.of("minecraft:MOOSHROOM");
    public static final Key GOAT = Key.of("minecraft:GOAT");
    public static final Key PIG = Key.of("minecraft:PIG");
    public static final Key STRIDER = Key.of("minecraft:STRIDER");
    public static final Key WOLF = Key.of("minecraft:WOLF");
    public static final Key CAT = Key.of("minecraft:CAT");
    public static final Key PARROT = Key.of("minecraft:PARROT");
    public static final Key ACACIA_BOAT = Key.of("minecraft:ACACIA_BOAT");
    public static final Key BAMBOO_BOAT = Key.of("minecraft:BAMBOO_BOAT");
    public static final Key BIRCH_BOAT = Key.of("minecraft:BIRCH_BOAT");
    public static final Key CHERRY_BOAT = Key.of("minecraft:CHERRY_BOAT");
    public static final Key DARK_OAK_BOAT = Key.of("minecraft:DARK_OAK_BOAT");
    public static final Key JUNGLE_BOAT = Key.of("minecraft:JUNGLE_BOAT");
    public static final Key MANGROVE_BOAT = Key.of("minecraft:MANGROVE_BOAT");
    public static final Key OAK_BOAT = Key.of("minecraft:OAK_BOAT");
    public static final Key SPRUCE_BOAT = Key.of("minecraft:SPRUCE_BOAT");
    public static final Key MINECART = Key.of("minecraft:MINECART");
    public static final Key HAPPY_GHAST = Key.of("minecraft:HAPPY_GHAST");
    public static final Key PIGLIN = Key.of("minecraft:PIGLIN");
    public static final Key CREEPER = Key.of("minecraft:CREEPER");
    public static final Key ALLAY = Key.of("minecraft:ALLAY");
    public static final Key HORSE = Key.of("minecraft:HORSE");
    public static final Key ZOMBIE_HORSE = Key.of("minecraft:ZOMBIE_HORSE");
    public static final Key SKELETON_HORSE = Key.of("minecraft:SKELETON_HORSE");
    public static final Key DONKEY = Key.of("minecraft:DONKEY");
    public static final Key MULE = Key.of("minecraft:MULE");
    public static final Key VILLAGER = Key.of("minecraft:VILLAGER");
    public static final Key WANDERING_TRADER = Key.of("minecraft:WANDERING_TRADER");
    public static final Key LLAMA = Key.of("minecraft:LLAMA");
    public static final Key TRADER_LLAMA = Key.of("minecraft:TRADER_LLAMA");
    public static final Key CAMEL = Key.of("minecraft:CAMEL");
    public static final Key ITEM_FRAME = Key.of("minecraft:ITEM_FRAME");
    public static final Key GLOW_ITEM_FRAME = Key.of("minecraft:GLOW_ITEM_FRAME");
    public static final Key INTERACTION = Key.of("minecraft:INTERACTION");
    public static final Key ACACIA_CHEST_BOAT = Key.of("minecraft:ACACIA_CHEST_BOAT");
    public static final Key BAMBOO_CHEST_BOAT = Key.of("minecraft:BAMBOO_CHEST_BOAT");
    public static final Key BIRCH_CHEST_BOAT = Key.of("minecraft:BIRCH_CHEST_BOAT");
    public static final Key CHERRY_CHEST_BOAT = Key.of("minecraft:CHERRY_CHEST_BOAT");
    public static final Key DARK_OAK_CHEST_BOAT = Key.of("minecraft:DARK_OAK_CHEST_BOAT");
    public static final Key JUNGLE_CHEST_BOAT = Key.of("minecraft:JUNGLE_CHEST_BOAT");
    public static final Key MANGROVE_CHEST_BOAT = Key.of("minecraft:MANGROVE_CHEST_BOAT");
    public static final Key OAK_CHEST_BOAT = Key.of("minecraft:OAK_CHEST_BOAT");
    public static final Key SPRUCE_CHEST_BOAT = Key.of("minecraft:SPRUCE_CHEST_BOAT");
    public static final Key CHEST_MINECART = Key.of("minecraft:CHEST_MINECART");
    public static final Key FURNACE_MINECART = Key.of("minecraft:FURNACE_MINECART");
    public static final Key HOPPER_MINECART = Key.of("minecraft:HOPPER_MINECART");
    public static final Key COMMAND_BLOCK_MINECART = Key.of("minecraft:COMMAND_BLOCK_MINECART");
    //＜1.20.5
    public static final Key MINECART_CHEST = Key.of("minecraft:MINECART_CHEST");
    public static final Key MINECART_FURNACE = Key.of("minecraft:MINECART_FURNACE");
    public static final Key MINECART_HOPPER = Key.of("minecraft:MINECART_HOPPER");
    public static final Key MINECART_COMMAND = Key.of("minecraft:MINECART_COMMAND");
}
